### ISSUE TITLE
Graphical bug when scrolling down.

### ISSUE THREAD

**Issue by etmoonshade** [angarg12/incremental_table_elements#9] opened 2016-10-20 14:19 UTC
https://dl.dropboxusercontent.com/u/22571912/Pics/Snips/IToE%20Graphical%20Bug.PNG

When scrolling down the page (once you've got enough to need to scroll,) the resource bar on the left side expands and covers part of the info in the middle. I'm able to reproduce this on IE11 and Pale Moon 26.3.3 (a Firefox fork from before the Australis UI, if you're not familiar with it.) This happens with both the Base and Cyborg themes as well.

**Comment by angarg12** [comment] 2016-10-20 15:14
I remember this one from a long time ago.

I took a quick look at it and didn't find the cause.

Considering that it is a minor graphical bug I won't work actively on solving it unless I can pinpoint the exact cause.

Thanks for reporting!

**Comment by angarg12** [comment] 2016-10-21 14:14
Apparently using width: auto in the affix element fixes the bug.

Will test and push.

**Comment by Josemite42** [comment] 2017-01-18 19:27
Any progress on this issue?  Can make things rather difficult to read:

http://imgur.com/a/iAntj

**Comment by angarg12** [comment] 2017-01-18 20:28
I think the fix that I mentioned before solves it, but to be honest I'm having a hard time reproducing this bug.

I can try to push the change and see how it works. Could you please provide more info in browser and OS so that I can try to reproduce in my local? Thanks!

**Comment by Josemite42** [comment] 2017-01-18 20:48
Problem occurs in both Chrome 55.0.2883.87 m and Internet Explorer 11.0.38.  OS is Windows 7 SP 1 and I'm currently at 1920 x 1080 resolution.  Switching to a 3:4 resolution appears to mitigate the issue (it still changes when the top tabs are off the screen, but doesn't overlap the center box).

**Comment by angarg12** [comment] 2017-01-18 21:02
That's great, thanks.

I just pushed a fix to prod. The width is set to auto and position is relative. In my local now the table is aligned perfectly.

Please report if the behaviour has changed.

**Comment by Josemite42** [comment] 2017-01-18 21:05
It's now aligned properly however its position is locked and doesn't float down when scrolling.

**Comment by angarg12** [comment] 2017-01-18 21:44
Pushed new changes.

Now it doesn´t overlap but is shown more squishy.

For some reason I can't make it work properly although it displays fine in my local.

**Comment by etmoonshade** [comment] 2017-01-18 21:45
I'm seeing the same thing as @angarg12 - it doesn't overlap on either theme when scrolling down, but the box contracts a bit (about 10-20 pixels, I'd say?) when scrolling. This is vastly preferable to covering up some of the UI, of course. :)

**Comment by Josemite42** [comment] 2017-01-18 22:00
Just reloaded, problem appears to be back.  I'm guessing it's resolution-specific?

http://imgur.com/a/emB2S


On a side note, just beat the game, rather enjoyed it!  Looking forward to an expanded game or more in the vein of a focus on complexity and paradigm shifts, just my kind of thing :)

**Comment by etmoonshade** [comment] 2017-01-18 22:25
@Josemite42: Ah-hah, I see it. If you get the window width down to about 1280 or 1400 (having to guess here,) whatever it is that makes the scrollbar show up, the sidebar covers everything now.

**Comment by angarg12** [comment] 2017-01-18 22:48
My current screen doesn't support FullHD so I can't test with very wide resolutions. Maybe I can try on a different computer at some other time.

@Josemite42 I'm glad that you enjoyed it. As you can see I am currently active refactoring all the code. More content is in the horizon, but no estimation at the moment.

**Comment by angarg12** [comment] 2017-01-25 14:35
Since hotfixes have been issued to prod and the GUI will get an overhaul in next versions, I will close this issue for the time being.

**Closed as completed by angarg12** 2017-01-25 14:35 UTC
Labels: bug
