### ISSUE TITLE
Dark matter prestige collection does not reset stats

### ISSUE THREAD

**Issue by Kasci** [angarg12/incremental_table_elements#187] opened 2018-05-02 12:59 UTC
On sidebar 3He, in game ammount of xN is also not reset and on first exotic run is bonus applied.

Steps to replicate (xN problem):
1. Achieve N
2. Gain some xN (best to see at least 1e6)
3. Run few exotic runs
4. Collect dark prestige
5. Start another exotic run with N
6. Bonus of xN is applied from previous dark run

**Comment by angarg12** [comment] 2018-05-02 16:40
Acknowledged, I will try to reproduce it today.

**Comment by angarg12** [comment] 2018-05-03 05:56
Haven't been able to reproduce with xH.

I can try with xN to see if there is anything special about it, or with more than 1 element.

If you send me the buggy save that would also work.

EDIT:

I have tried it with a combination of H and N and still can't reproduce it. If you send me the save and tell me what to look for I'll really appreciate it.

**Comment by Kasci** [comment] 2018-05-03 09:50
Probably alignment of stars ... Neither of those I couldnt replicate again .... maybe something happened but now it is fixed (or at least not reproducible) :D ...

**Comment by angarg12** [comment] 2018-05-03 15:54
I'll close this issue then.

**Closed as completed by angarg12** 2018-05-03 15:54 UTC
Labels: bug
