### ISSUE TITLE
Incorrect decay due to missing isotopes

### ISSUE THREAD

**Issue by primeprover** [angarg12/incremental_table_elements#182] opened 2018-02-08 13:41 UTC
Currently if an element decays into an isotope that isn't in the game it instead decays into the isotope that is "closest". For example 210Rn decays via alpha decay to 206Po according to http://periodictable.com/Isotopes/086.210/index2.p.full.dm.prod.html , however, 206Po isn't in the game. It appears that it ends up decaying to 208Po. A better solution would be for it to end up decaying straight to the next ingame isotopes in the chain(206Pb, 202Hg and 198Hg) with adjusted probabilities. 
A lot of these will be corrected when I add more isotopes but I would imagine that there will still be cases. Maybe we should add isotopes if it would fix this issue even if they have a really short half life.

**Comment by angarg12** [comment] 2018-02-08 20:45
This is by design.

When decay is to an isotope that isn't in the game, we find the closes isotope and decay to that one instead. The reason is that this situation happens fairly often (we can double check how often) and we had to make a call between being 100% scientifically accurate (removing a lot of content in the process) or be more lenient.

The solution that you propose is an alternative, but it may still run into the problem that next isotopes still aren't in the game, which just delays and doesn't really solve the problem. It also introduces the issue of how to input the decay chain for an specific isotope; I can see that becoming very messy very quickly.

You could run the numbers and make a concrete proposal. If there is a significant improvement in the content we could consider it. At the moment I am satisfied with the current implementation.

**Comment by primeprover** [comment] 2018-02-08 22:13
I think my current preference is to attempt to remove the issue by adding whatever isotopes are missing even if they wouldn't otherwise be added. I don't think that there will be a too ridiculous list of them. We will see once I have added all the isotopes. 
It is a very difficult problem to solve in a sane way.
BTW my previous solution will always work although you might need to work down the chain as we will have all stable isotopes which are the endpoints of each chain. I was thinking that if necessary rather than a beta decay to a missing isotope and then another beta decay to a known isotope just code in a double beta decay(chains/trees can be longer than this). This shouldn't be too hard as long as more complex forms of decay can be added.

Do you have a way of listing when it happens? Then we can have an idea of the scale of the problem.

**Comment by angarg12** [comment] 2018-02-19 21:38
> Do you have a way of listing when it happens? Then we can have an idea of the scale of the problem.

Can definitely do that in the build script. I'll write back the results of a run.

**Comment by angarg12** [comment] 2018-02-19 22:02
The results are here:

https://pastebin.com/HZdnu5vW

There are 75 missed decays. Generally they are not too bad, but there is about 7 of distance > 4 missing decays that could be quite bad.

**Comment by angarg12** [comment] 2018-03-21 08:53
There is an excellent work in progress from @primeprover on this issue so I am going to close it for the time being.

**Closed as completed by angarg12** 2018-03-21 08:53 UTC
Labels: bug, enhancement
